#pragma once

// Manifests
#define ID_MANIFEST 1

// Icons
#define ID_ICON_APP 1

// Images
#define ID_IMAGE_BASSIEBASE 1

// Strings
#define ID_STRING_MENU_ABOUT 1
#define ID_STRING_DRAG_IMAGE 2
#define ID_STRING_IMAGE_LOADING 3
#define ID_STRING_IMAGE_ERROR 4
#define ID_STRING_FOOTER 5
#define ID_STRING_ABOUT_HEADER 6
#define ID_STRING_ABOUT_DESCRIPTION 7
#define ID_STRING_ABOUT_COPYRIGHT 8
#define ID_STRING_OPEN_FILE 9
#define ID_STRING_OPEN_FILES_FILTER 10
