#ifndef REDSQUARE_H
#define REDSQUARE_H

// Utils
#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

// Version
#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 4

// Icons
#define APP_ICON_ID 1

// Bitmaps
#define PAPER_BITMAP_ID 1

// Sounds
#define GAMEOVER_WAVE_ID 1

// Strings
#define MENU_PLAY_STRING_ID 1
#define MENU_HIGHSCORES_STRING_ID 2
#define MENU_HELP_STRING_ID 3
#define MENU_SETTINGS_STRING_ID 4
#define MENU_EXIT_STRING_ID 5
#define MENU_FOOTER_STRING_ID 6
#define GAME_SCORE_STRING_ID 7
#define GAME_TIME_STRIND_ID 8
#define GAME_LEVEL_STRING_ID 9
#define GAMEOVER_TITLE_STRING_ID 10
#define BACK_STRING_ID 11
#define HIGHSCORES_EMPTY_STRING_ID 12
#define HELP_TEXT_STRING_ID 13
#define HELP_TEXT_LINES 6
#define SETTINGS_NAME_STRING_ID 14
#define SETTINGS_LANGUAGE_STRING_ID 15

// Manifest
#define MANIFEST_ID 1

#endif
